server {
	listen 443 ssl;
	listen [::]:443 ssl;
	server_name sboukiou.42.fr;

	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_certificate /etc/nginx/ssl/inception.crt;
	ssl_certificate_key /etc/nginx/ssl/inception.key;

	root /var/www/wordpress;
	index index.php index.html;

	location / {
		try_files $uri $uri/ /index.php?$args;
	}
	location ~ \.php$ {
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		fastcgi_pass wordpress:9000;
		fastcgi_index index.php;
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param PATH_INFO $fastcgi_path_info;
	}
	location ~ ^/adminer(/.*$|$) {
		# FastCGI configuration to pass PHP requests to the Adminer container
		fastcgi_split_path_info ^(/adminer)(/.*)$;
		fastcgi_pass adminer:8090;
		fastcgi_index index.php;
		include fastcgi_params;

		# Mandatory: Map the SCRIPT_FILENAME so Adminer knows which file to run
		fastcgi_param SCRIPT_FILENAME /var/www/html/index.php;
		fastcgi_param PATH_INFO $fastcgi_path_info;

		# Optional: Basic Authentication (if you want NGINX to handle it)
		# auth_basic "Adminer Secret Area";
		# auth_basic_user_file /etc/nginx/.htpasswd;
	}
}
