services:

  mariadb:
    build:
    container_name: mariadb
    image: mariadb
    restart:
    volumes:
    networks:
    env_file: ../.env
    secrets:

  wordpress:
    build:
    container_name: wordpress
    image: wordpress
    restart:
    volumes:
    networks:
    depends_on:
      - mariadb
    env_file: ../.env
    secrets:

  nginx:
    build:
    container_name: nginx
    image: nginx
    restart:
    ports:
      - "443:443"
    volumes:
    networks:
    depends_on:
      - wordpress
    env_file: ../.env
    secrets:


networks:
  inception:
    driver: bridge

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: "/home/sboukiou/data/wordpress"
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: "/home/sboukiou/data/mariadb"
      o: bind




secrets:
  db_password:
    file:
  db_root_password:
    file:
  wp_password:
    file:
  wp_admin_password:
    file:

