[www]
; The user and group the process will run under
user = www-data
group = www-data

; The address on which to accept FastCGI requests. 
; We use 0.0.0.0 to listen on all interfaces within the container network.
listen = 0.0.0.0:8090

; Process management settings
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; Mandatory for Inception: Ensures environment variables (like DB host) 
; are accessible to the PHP script.
clear_env = no
